name: Prueba self-hosted runner

on:
  push:

jobs:
  comparar-tokens:
    runs-on: self-hosted

    steps:
      - name: Comparar DEV_TOKEN
        shell: powershell
        env:
          DEV_TOKEN: ${{ secrets.DEV_TOKEN }}
        run: |
          $localToken = $env:LOCAL_DEV_TOKEN

          if ($env:DEV_TOKEN -eq $localToken) {
            Write-Host "Los tokens coinciden"
          }
          else {
            Write-Host "Los tokens NO coinciden"
            exit 1
          }
